// Code generated by ent, DO NOT EDIT.

package series

import (
	"polaris/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldID, id))
}

// TmdbID applies equality check predicate on the "tmdb_id" field. It's identical to TmdbIDEQ.
func TmdbID(v int) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTmdbID, v))
}

// ImdbID applies equality check predicate on the "imdb_id" field. It's identical to ImdbIDEQ.
func ImdbID(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldImdbID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitle, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldOriginalName, v))
}

// Overview applies equality check predicate on the "overview" field. It's identical to OverviewEQ.
func Overview(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldOverview, v))
}

// Path applies equality check predicate on the "path" field. It's identical to PathEQ.
func Path(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldPath, v))
}

// TmdbIDEQ applies the EQ predicate on the "tmdb_id" field.
func TmdbIDEQ(v int) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTmdbID, v))
}

// TmdbIDNEQ applies the NEQ predicate on the "tmdb_id" field.
func TmdbIDNEQ(v int) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldTmdbID, v))
}

// TmdbIDIn applies the In predicate on the "tmdb_id" field.
func TmdbIDIn(vs ...int) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldTmdbID, vs...))
}

// TmdbIDNotIn applies the NotIn predicate on the "tmdb_id" field.
func TmdbIDNotIn(vs ...int) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldTmdbID, vs...))
}

// TmdbIDGT applies the GT predicate on the "tmdb_id" field.
func TmdbIDGT(v int) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldTmdbID, v))
}

// TmdbIDGTE applies the GTE predicate on the "tmdb_id" field.
func TmdbIDGTE(v int) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldTmdbID, v))
}

// TmdbIDLT applies the LT predicate on the "tmdb_id" field.
func TmdbIDLT(v int) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldTmdbID, v))
}

// TmdbIDLTE applies the LTE predicate on the "tmdb_id" field.
func TmdbIDLTE(v int) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldTmdbID, v))
}

// ImdbIDEQ applies the EQ predicate on the "imdb_id" field.
func ImdbIDEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldImdbID, v))
}

// ImdbIDNEQ applies the NEQ predicate on the "imdb_id" field.
func ImdbIDNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldImdbID, v))
}

// ImdbIDIn applies the In predicate on the "imdb_id" field.
func ImdbIDIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldImdbID, vs...))
}

// ImdbIDNotIn applies the NotIn predicate on the "imdb_id" field.
func ImdbIDNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldImdbID, vs...))
}

// ImdbIDGT applies the GT predicate on the "imdb_id" field.
func ImdbIDGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldImdbID, v))
}

// ImdbIDGTE applies the GTE predicate on the "imdb_id" field.
func ImdbIDGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldImdbID, v))
}

// ImdbIDLT applies the LT predicate on the "imdb_id" field.
func ImdbIDLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldImdbID, v))
}

// ImdbIDLTE applies the LTE predicate on the "imdb_id" field.
func ImdbIDLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldImdbID, v))
}

// ImdbIDContains applies the Contains predicate on the "imdb_id" field.
func ImdbIDContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldImdbID, v))
}

// ImdbIDHasPrefix applies the HasPrefix predicate on the "imdb_id" field.
func ImdbIDHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldImdbID, v))
}

// ImdbIDHasSuffix applies the HasSuffix predicate on the "imdb_id" field.
func ImdbIDHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldImdbID, v))
}

// ImdbIDEqualFold applies the EqualFold predicate on the "imdb_id" field.
func ImdbIDEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldImdbID, v))
}

// ImdbIDContainsFold applies the ContainsFold predicate on the "imdb_id" field.
func ImdbIDContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldImdbID, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldTitle, v))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldOriginalName, v))
}

// OverviewEQ applies the EQ predicate on the "overview" field.
func OverviewEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldOverview, v))
}

// OverviewNEQ applies the NEQ predicate on the "overview" field.
func OverviewNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldOverview, v))
}

// OverviewIn applies the In predicate on the "overview" field.
func OverviewIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldOverview, vs...))
}

// OverviewNotIn applies the NotIn predicate on the "overview" field.
func OverviewNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldOverview, vs...))
}

// OverviewGT applies the GT predicate on the "overview" field.
func OverviewGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldOverview, v))
}

// OverviewGTE applies the GTE predicate on the "overview" field.
func OverviewGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldOverview, v))
}

// OverviewLT applies the LT predicate on the "overview" field.
func OverviewLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldOverview, v))
}

// OverviewLTE applies the LTE predicate on the "overview" field.
func OverviewLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldOverview, v))
}

// OverviewContains applies the Contains predicate on the "overview" field.
func OverviewContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldOverview, v))
}

// OverviewHasPrefix applies the HasPrefix predicate on the "overview" field.
func OverviewHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldOverview, v))
}

// OverviewHasSuffix applies the HasSuffix predicate on the "overview" field.
func OverviewHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldOverview, v))
}

// OverviewEqualFold applies the EqualFold predicate on the "overview" field.
func OverviewEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldOverview, v))
}

// OverviewContainsFold applies the ContainsFold predicate on the "overview" field.
func OverviewContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldOverview, v))
}

// PathEQ applies the EQ predicate on the "path" field.
func PathEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldEQ(FieldPath, v))
}

// PathNEQ applies the NEQ predicate on the "path" field.
func PathNEQ(v string) predicate.Series {
	return predicate.Series(sql.FieldNEQ(FieldPath, v))
}

// PathIn applies the In predicate on the "path" field.
func PathIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldIn(FieldPath, vs...))
}

// PathNotIn applies the NotIn predicate on the "path" field.
func PathNotIn(vs ...string) predicate.Series {
	return predicate.Series(sql.FieldNotIn(FieldPath, vs...))
}

// PathGT applies the GT predicate on the "path" field.
func PathGT(v string) predicate.Series {
	return predicate.Series(sql.FieldGT(FieldPath, v))
}

// PathGTE applies the GTE predicate on the "path" field.
func PathGTE(v string) predicate.Series {
	return predicate.Series(sql.FieldGTE(FieldPath, v))
}

// PathLT applies the LT predicate on the "path" field.
func PathLT(v string) predicate.Series {
	return predicate.Series(sql.FieldLT(FieldPath, v))
}

// PathLTE applies the LTE predicate on the "path" field.
func PathLTE(v string) predicate.Series {
	return predicate.Series(sql.FieldLTE(FieldPath, v))
}

// PathContains applies the Contains predicate on the "path" field.
func PathContains(v string) predicate.Series {
	return predicate.Series(sql.FieldContains(FieldPath, v))
}

// PathHasPrefix applies the HasPrefix predicate on the "path" field.
func PathHasPrefix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasPrefix(FieldPath, v))
}

// PathHasSuffix applies the HasSuffix predicate on the "path" field.
func PathHasSuffix(v string) predicate.Series {
	return predicate.Series(sql.FieldHasSuffix(FieldPath, v))
}

// PathEqualFold applies the EqualFold predicate on the "path" field.
func PathEqualFold(v string) predicate.Series {
	return predicate.Series(sql.FieldEqualFold(FieldPath, v))
}

// PathContainsFold applies the ContainsFold predicate on the "path" field.
func PathContainsFold(v string) predicate.Series {
	return predicate.Series(sql.FieldContainsFold(FieldPath, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Series) predicate.Series {
	return predicate.Series(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Series) predicate.Series {
	return predicate.Series(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Series) predicate.Series {
	return predicate.Series(sql.NotPredicates(p))
}
