// Code generated by ent, DO NOT EDIT.

package indexers

import (
	"polaris/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Indexers {
	return predicate.Indexers(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Indexers {
	return predicate.Indexers(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Indexers {
	return predicate.Indexers(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldName, v))
}

// Implementation applies equality check predicate on the "implementation" field. It's identical to ImplementationEQ.
func Implementation(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldImplementation, v))
}

// Settings applies equality check predicate on the "settings" field. It's identical to SettingsEQ.
func Settings(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldSettings, v))
}

// EnableRss applies equality check predicate on the "enable_rss" field. It's identical to EnableRssEQ.
func EnableRss(v bool) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldEnableRss, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldPriority, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContainsFold(FieldName, v))
}

// ImplementationEQ applies the EQ predicate on the "implementation" field.
func ImplementationEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldImplementation, v))
}

// ImplementationNEQ applies the NEQ predicate on the "implementation" field.
func ImplementationNEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldImplementation, v))
}

// ImplementationIn applies the In predicate on the "implementation" field.
func ImplementationIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldIn(FieldImplementation, vs...))
}

// ImplementationNotIn applies the NotIn predicate on the "implementation" field.
func ImplementationNotIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNotIn(FieldImplementation, vs...))
}

// ImplementationGT applies the GT predicate on the "implementation" field.
func ImplementationGT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGT(FieldImplementation, v))
}

// ImplementationGTE applies the GTE predicate on the "implementation" field.
func ImplementationGTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGTE(FieldImplementation, v))
}

// ImplementationLT applies the LT predicate on the "implementation" field.
func ImplementationLT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLT(FieldImplementation, v))
}

// ImplementationLTE applies the LTE predicate on the "implementation" field.
func ImplementationLTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLTE(FieldImplementation, v))
}

// ImplementationContains applies the Contains predicate on the "implementation" field.
func ImplementationContains(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContains(FieldImplementation, v))
}

// ImplementationHasPrefix applies the HasPrefix predicate on the "implementation" field.
func ImplementationHasPrefix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasPrefix(FieldImplementation, v))
}

// ImplementationHasSuffix applies the HasSuffix predicate on the "implementation" field.
func ImplementationHasSuffix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasSuffix(FieldImplementation, v))
}

// ImplementationEqualFold applies the EqualFold predicate on the "implementation" field.
func ImplementationEqualFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEqualFold(FieldImplementation, v))
}

// ImplementationContainsFold applies the ContainsFold predicate on the "implementation" field.
func ImplementationContainsFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContainsFold(FieldImplementation, v))
}

// SettingsEQ applies the EQ predicate on the "settings" field.
func SettingsEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldSettings, v))
}

// SettingsNEQ applies the NEQ predicate on the "settings" field.
func SettingsNEQ(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldSettings, v))
}

// SettingsIn applies the In predicate on the "settings" field.
func SettingsIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldIn(FieldSettings, vs...))
}

// SettingsNotIn applies the NotIn predicate on the "settings" field.
func SettingsNotIn(vs ...string) predicate.Indexers {
	return predicate.Indexers(sql.FieldNotIn(FieldSettings, vs...))
}

// SettingsGT applies the GT predicate on the "settings" field.
func SettingsGT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGT(FieldSettings, v))
}

// SettingsGTE applies the GTE predicate on the "settings" field.
func SettingsGTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldGTE(FieldSettings, v))
}

// SettingsLT applies the LT predicate on the "settings" field.
func SettingsLT(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLT(FieldSettings, v))
}

// SettingsLTE applies the LTE predicate on the "settings" field.
func SettingsLTE(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldLTE(FieldSettings, v))
}

// SettingsContains applies the Contains predicate on the "settings" field.
func SettingsContains(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContains(FieldSettings, v))
}

// SettingsHasPrefix applies the HasPrefix predicate on the "settings" field.
func SettingsHasPrefix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasPrefix(FieldSettings, v))
}

// SettingsHasSuffix applies the HasSuffix predicate on the "settings" field.
func SettingsHasSuffix(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldHasSuffix(FieldSettings, v))
}

// SettingsEqualFold applies the EqualFold predicate on the "settings" field.
func SettingsEqualFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldEqualFold(FieldSettings, v))
}

// SettingsContainsFold applies the ContainsFold predicate on the "settings" field.
func SettingsContainsFold(v string) predicate.Indexers {
	return predicate.Indexers(sql.FieldContainsFold(FieldSettings, v))
}

// EnableRssEQ applies the EQ predicate on the "enable_rss" field.
func EnableRssEQ(v bool) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldEnableRss, v))
}

// EnableRssNEQ applies the NEQ predicate on the "enable_rss" field.
func EnableRssNEQ(v bool) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldEnableRss, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.Indexers {
	return predicate.Indexers(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.Indexers {
	return predicate.Indexers(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.Indexers {
	return predicate.Indexers(sql.FieldLTE(FieldPriority, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Indexers) predicate.Indexers {
	return predicate.Indexers(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Indexers) predicate.Indexers {
	return predicate.Indexers(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Indexers) predicate.Indexers {
	return predicate.Indexers(sql.NotPredicates(p))
}
