// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DownloadClients is the predicate function for downloadclients builders.
type DownloadClients func(*sql.Selector)

// Epidodes is the predicate function for epidodes builders.
type Epidodes func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// Indexers is the predicate function for indexers builders.
type Indexers func(*sql.Selector)

// Series is the predicate function for series builders.
type Series func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)
